### ISSUE TITLE
selectizeInput with bulma UI?

### ISSUE THREAD

**Issue by tylerlittlefield** [JohnCoene/shinybulma#41]
I would like to use `shiny::selectizeInput` for server side processing. Is there an easy way to apply some of the bulma UI to `shiny::selectizeInput`?

**Comment by tylerlittlefield** [comment]
Looks like I can get it to look somewhat similar with:

```css
.control-label {
  margin-bottom: 0.5em;
  color: #363636;
  display: block;
  font-size: 1rem;
  font-weight: 700;
}

.selectize-input {
  padding: 9px 12px;
}
```
